G_SCREEN_WIDTH		= 800 # Not-fullscreen window size
G_SCREEN_HEIGHT		= 600
GAP					= 10 # Gap between the window border/status bar and the players
STATUS_BAR			= 50 # Size of the status bar
STATUS_BAR_COLOUR	= (50,50,50) # Status bar colour
BACKGROUND_COLOUR	= (0,0,0) # Background colour
P1_MOVE				= 6 # Move speed of the players
P2_MOVE				= 6 # ^^
SPRITE_SIZE			= 55 # The pixel size of the sprites used in the spritesheets
SPRITE_COOLDOWN		= 60 # How long it takes to change to a different frame of a spritesheet
BULLET_SPEED		= 10 # Pew pew
FIRE_COOLDOWN		= 360 # How long it takes to 
PLAYER_LIFE			= 3 # Number of hearts
EXPLOSION_COOLDOWN	= 300 # Explosion sprite change cooldown
BLOCK_WIDTH			= 100 # Width of blocks
BLOCK_HEIGHT		= 30 # Height of blocks
BLOCK_COLOUR		= (50,50,50) # Colour of blocks
BLOCK_SPEED			= 2 # Speed of blocks
BLOCK_NUMBER		= 5 # Number of blocks
BOMB_SPEED			= 5 # Bomb speed
BOMB_COOLDOWN		= 2000 # Cooldown between bomb deployments
NUMBER_OF_BOMBS		= 3 # Number of bombs per player
AI_SPEED			= 16 # For the trackin AI version